<!--                                                       -->
<!-- $Id: paypal.php 259 2006-01-05 16:06:14Z sgrayban $ -->
<!--                                                       -->
<script type="text/javascript"><!--
google_ad_client = "pub-6947168901384509";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_type = "text_image";
google_ad_channel ="2405125847";
google_color_border = "669966";
google_color_bg = "99CC99";
google_color_link = "000000";
google_color_url = "00008B";
google_color_text = "336633";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<h2>Donate to CastPodder&reg;&trade;</h2>
<p>
We are volunteers. And we offer CastPodder for free. We believe this new way of getting content should be available for everyone, not controlled by narrow interests. Our work is entirely supported by donations by cool people like you. If you can give something, we would really appreciate it. [It's good karma, and great things will happen to you the rest of your life. :) ] Donations will continue to be used wisely in the development of CastPodder, and supporting BorgForge. Your support is appreciated—thank you!
<br /><br />
Please note:</b>(You do not need to login if you want your donation to be anonymous.)
<br /><br />
<a href="/pics/index.html" target="_blank">This</a> is one reason why we need donations.
</p>
<b>Click on one of the PayPal buttons below to donate money to <a href="http://borgforge.net/projects/castpodder/">CastPodder</a>&reg;&trade;, A linux podcast receiver.</b>
<br /><br />
<table width=50% border="0">
        <tr>
                <td align="center">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but04.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIIAQYJKoZIhvcNAQcEoIIH8jCCB+4CAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYBY9L6avYI47qHKzdVM6rstXfEj2ZH1t13iks2s6sz7XRvZcX/eYx1rxULfAxfuZmCAc/laOY6FzUhSObtEGYdjKjog3mSU1p14T2E3r53/dCfcLGxIkTR7Qtzc0zvEkNxwMieYwojAOmzP4bVZO/ypSMAP6gd3PsiywtJjs7BhHzELMAkGBSsOAwIaBQAwggF9BgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECO3RN20ykDgrgIIBWIaZuSEgfbhSUiYtz9UmIJJC9Zp2OfaC2UulMq7IVUcOYCssaSYEpKRyUWf0kIEHFaOYJIJ+0/yNntTxZ51+TYQVwfTXT8qvMKVJEOULy79355zkIJcIJE5lh3iYWggbw7VKEupuPZsDezOL+8JDhavjQgyhTRXG44daW/7bPfm3MrJZdSQzeKIV57vNordLHwO798cIjlmbMVzRdxvi02C+YfV+tg/lfK26yhLfmNjbEtqqXMKvfpmqF6Wzj+n3L9cfxVlAsdA2FOWGwVYWrSF4HMTPKUfkdx5l8sNh1FGiXCa22uFLsviRTpVE3KnEbjGOda/lgqLhwlyg0a/JRWmzMz8uRM2QUkKyaWUvhNyCezjh+kacYdcuvE7LNIVQ1uBJ5+un4r6jbssny5/+1MiUpRLz8biFb4w4kR9DIFXAnZP1tGwx/HEvOFyz0dHfzA79SQyvG9UFoIIDhzCCA4MwggLsoAMCAQICAQAwDQYJKoZIhvcNAQEFBQAwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMB4XDTA0MDIxMzEwMTMxNVoXDTM1MDIxMzEwMTMxNVowgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBR07d/ETMS1ycjtkpkvjXZe9k+6CieLuLsPumsJ7QC1odNz3sJiCbs2wC0nLE0uLGaEtXynIgRqIddYCHx88pb5HTXv4SZeuv0Rqq4+axW9PLAAATU8w04qqjaSXgbGLP3NmohqM6bV9kZZwZLR/klDaQGo1u9uDb9lr4Yn+rBQIDAQABo4HuMIHrMB0GA1UdDgQWBBSWn3y7xm8XvVk/UtcKG+wQ1mSUazCBuwYDVR0jBIGzMIGwgBSWn3y7xm8XvVk/UtcKG+wQ1mSUa6GBlKSBkTCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb22CAQAwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQCBXzpWmoBa5e9fo6ujionW1hUhPkOBakTr3YCDjbYfvJEiv/2P+IobhOGJr85+XHhN0v4gUkEDI8r2/rNk1m0GA8HKddvTjyGw/XqXa+LSTlDYkqI8OwR8GEYj4efEtcRpRYBxV8KxAW93YDWzFGvruKnnLbDAF6VR5w/cCMn5hzGCAZowggGWAgEBMIGUMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbQIBADAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMDUxMDExMDcwMDM5WjAjBgkqhkiG9w0BCQQxFgQUITbV9VxGrVJpnOMaE7zg8aNfEkcwDQYJKoZIhvcNAQEBBQAEgYAPmA4Ggu6PUbhz39mSpOt2pxkJxs8MqzH9iqUgqUBjC5bHsermVWjck1P6bHEiylAYPNofYQ6TlOpptdVVsI8A7yPhofu13Q1sJXBbKk0RIyLI93WttG0/wf6C4Hulx6vv31DDK7WaT82DE5qXs8+EjOaPPRS4JG7hKbo/zs0wZw==-----END PKCS7-----">
</form></td>
                <td align="center">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but04.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHyQYJKoZIhvcNAQcEoIIHujCCB7YCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYAA0A9e+3R5zBGsUrHY46QAcTUz9QmrTAQ6t0g5xsfvly/fgGaT6dJi49n1Wb+4j3CVxO/uJ0A/S1eQr/9tgWpor5As61kA01b+yVD8rv1LMWYKjP+Vy9db+jAIxpwjn2mLMp2KHMYEZCwrjOEpTVa00e+igVQ9vLLbAo9hT+TgLzELMAkGBSsOAwIaBQAwggFFBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECFIviaWtsFBsgIIBIOho5Dj913wFKWOdAvfmIzaARAbXRvUFVqMF68qD+89fnwUfPzIKqrtOf9eFLLPE8gHhmKFrLlSko+ef1ors74t/hVssGXIPD619KWfaiqQXyorxXbfM9P31qLHlkdRFjNbZ9B9SyhNJMeuBKhqH6IGpqmCsIgf0oPbk/TWj+kyzCXBX8fSvk00HdgVfc2HpNVwEtGMeFU9/R1t86aE53QeVpyCGZAMA9kO3vBae95FwbjDglFC99bo4DPF/qg3bvEgOXSYLCO0814shMM94EoG6wKJxZxE5ZwIgzXQKgJN6+suRKPXpny7KwZDYETCSbVy6HHopp2Rs97A8XsflDzVAcJY5rz2ELUxaCl9zQxqtaTxstMprDLJc77AaxRelh6CCA4cwggODMIIC7KADAgECAgEAMA0GCSqGSIb3DQEBBQUAMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTAeFw0wNDAyMTMxMDEzMTVaFw0zNTAyMTMxMDEzMTVaMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAwUdO3fxEzEtcnI7ZKZL412XvZPugoni7i7D7prCe0AtaHTc97CYgm7NsAtJyxNLixmhLV8pyIEaiHXWAh8fPKW+R017+EmXrr9EaquPmsVvTywAAE1PMNOKqo2kl4Gxiz9zZqIajOm1fZGWcGS0f5JQ2kBqNbvbg2/Za+GJ/qwUCAwEAAaOB7jCB6zAdBgNVHQ4EFgQUlp98u8ZvF71ZP1LXChvsENZklGswgbsGA1UdIwSBszCBsIAUlp98u8ZvF71ZP1LXChvsENZklGuhgZSkgZEwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tggEAMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAgV86VpqAWuXvX6Oro4qJ1tYVIT5DgWpE692Ag422H7yRIr/9j/iKG4Thia/Oflx4TdL+IFJBAyPK9v6zZNZtBgPBynXb048hsP16l2vi0k5Q2JKiPDsEfBhGI+HnxLXEaUWAcVfCsQFvd2A1sxRr67ip5y2wwBelUecP3AjJ+YcxggGaMIIBlgIBATCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTA1MTAxMTA3MjIzMVowIwYJKoZIhvcNAQkEMRYEFG+P1iiNe3jm/ENbrE/eSHSEN8hiMA0GCSqGSIb3DQEBAQUABIGAnegfCOuRUnmABRGyG+LwH/xLs42JGtjRzZn4kq0gVao+rBv3RZI4IpOfavE0U8CpwXz0I0UogA9TCrtbhLtg8sA5RecOlndRo5AaXMmz92bBvWtFiS74AWYp7JnSLjfq55hpdPrGFWFbTHfdOcip+8Cs+G/BCoy1eX6JwNk1w/0=-----END PKCS7-----">
</form></td>
                <td align="center">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but04.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHyQYJKoZIhvcNAQcEoIIHujCCB7YCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYBpIvSEMcIy+VGkIszgwQRxIoXENIRz7gtKHHN7aNbXaI5QkspFLmVGN/WeJ9COARwIXf7Qe6W2T9K3QSyad1m6WMxgg9mI99renJfc/b0U9ILak3McUV/jjIPYqRqKSYx71r1ClXfYzDxexQCKRKnIYIwgeWIpkK7os2M3VKQ8gzELMAkGBSsOAwIaBQAwggFFBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECGFapx0qBIq3gIIBICaMpg8Mi6KgP21+3cEKkMlBT4fWPSgf+ye9y8iIJjOA7/xYdbn+Cd8dp4cK0hKGkZOJXXMorHfgbpCR1+rpH+FUKiuOIkZaZbQtl3LoY1eScnobKbkMvLTH3yWxF+iPQtP0T6TzGzZ8zks8zSk8sZtZ3sQkAM2o9Z9XxoOAYxVlVwbwP1l8vrsumjlXCvBf2swRgMepDxhxU43zngq/12GLri2FO9GotQ2VBhemeos/G5Kw9mWWlfvgoF6G4u2jZCf76Fy4vP5tVXnlsg7PfUXFjPXmJ1ACEP8cqlkiQmIsMkh7Q4l8oRXDQicFohev5CsttfTiU7cZ+wvuQan8Ye/u87kIXX8ol8/5yYvuyX0VU3HbrNSbBE7CMFnYYzi7SqCCA4cwggODMIIC7KADAgECAgEAMA0GCSqGSIb3DQEBBQUAMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTAeFw0wNDAyMTMxMDEzMTVaFw0zNTAyMTMxMDEzMTVaMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAwUdO3fxEzEtcnI7ZKZL412XvZPugoni7i7D7prCe0AtaHTc97CYgm7NsAtJyxNLixmhLV8pyIEaiHXWAh8fPKW+R017+EmXrr9EaquPmsVvTywAAE1PMNOKqo2kl4Gxiz9zZqIajOm1fZGWcGS0f5JQ2kBqNbvbg2/Za+GJ/qwUCAwEAAaOB7jCB6zAdBgNVHQ4EFgQUlp98u8ZvF71ZP1LXChvsENZklGswgbsGA1UdIwSBszCBsIAUlp98u8ZvF71ZP1LXChvsENZklGuhgZSkgZEwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tggEAMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAgV86VpqAWuXvX6Oro4qJ1tYVIT5DgWpE692Ag422H7yRIr/9j/iKG4Thia/Oflx4TdL+IFJBAyPK9v6zZNZtBgPBynXb048hsP16l2vi0k5Q2JKiPDsEfBhGI+HnxLXEaUWAcVfCsQFvd2A1sxRr67ip5y2wwBelUecP3AjJ+YcxggGaMIIBlgIBATCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTA1MTAxMTA3MjU1OVowIwYJKoZIhvcNAQkEMRYEFMp9HSUWRYc5iRMLQAYcV4ZBInw0MA0GCSqGSIb3DQEBAQUABIGAFrGoFS8Iu1S2NtwKbZgIJarwiMBxsmOLtiMfGchwvbBv7feSa0RBtkQDRI359u6X9oe+lCEkH433VZAmOJ/q31lrDE+0jxQ+G+zGXg+Ml1nQCpsCueajHU/aeNh+qAVl+/Lyiuh7kr+1+WyVWix65b3b9rWqXZU8T9Z2wuN9PK4=-----END PKCS7-----">
</form></td>
                <td align="center">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but04.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHyQYJKoZIhvcNAQcEoIIHujCCB7YCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYAAWqfXp3ndWz9tNR8OrRE5D0Q2l9/VC4vD2pn2kjBdBuNBYUel8+3XAxTJTnWfe/wVKSt8za4J1SzQdAPocjGraacDTQdUWPDyuJWdJGZ2L0T3ijIftIJ5cBNNzRam+WeYkJ1eaBe3T5uz9W4yDPpjWHsMDh5Z+tk0K+aMttYgQzELMAkGBSsOAwIaBQAwggFFBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECM+UJ92thqKugIIBIHpC1XqeAiHre7eqWKHTxmtq7UYmHpdaVbViT6Q7KWdc3yQyH0iJP+bbxJA2/x8Hjqsrqir/NYdBZuMNRfrvKDFFTjbGKw+l4xIUr9/XLjCHgJQmTUWovtTWHDjAymocuwKWZjsff7jGcJqxRZ9YcgPoJQtNXy3eaqNKS6WvIxD2ZCP71rnTnqLuSgAPWctm75j2Arv09FdhDQ+7FYf9XT+QIRx8574R7Ep/ui8l0q7WD52gLpbqn9p6S3Px/oNvDIG/kYI9ay08KAwdnvUuhYJxzgSi2lTOX1nV65XXbLxQ2qPNUwWhSgzNJxxmRcCgjz0DXAML9hci7eyovRd8D6ZSAPwcqjps12BrEazT7rruERGPfRyetkseSZwTSCldUqCCA4cwggODMIIC7KADAgECAgEAMA0GCSqGSIb3DQEBBQUAMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTAeFw0wNDAyMTMxMDEzMTVaFw0zNTAyMTMxMDEzMTVaMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAwUdO3fxEzEtcnI7ZKZL412XvZPugoni7i7D7prCe0AtaHTc97CYgm7NsAtJyxNLixmhLV8pyIEaiHXWAh8fPKW+R017+EmXrr9EaquPmsVvTywAAE1PMNOKqo2kl4Gxiz9zZqIajOm1fZGWcGS0f5JQ2kBqNbvbg2/Za+GJ/qwUCAwEAAaOB7jCB6zAdBgNVHQ4EFgQUlp98u8ZvF71ZP1LXChvsENZklGswgbsGA1UdIwSBszCBsIAUlp98u8ZvF71ZP1LXChvsENZklGuhgZSkgZEwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tggEAMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAgV86VpqAWuXvX6Oro4qJ1tYVIT5DgWpE692Ag422H7yRIr/9j/iKG4Thia/Oflx4TdL+IFJBAyPK9v6zZNZtBgPBynXb048hsP16l2vi0k5Q2JKiPDsEfBhGI+HnxLXEaUWAcVfCsQFvd2A1sxRr67ip5y2wwBelUecP3AjJ+YcxggGaMIIBlgIBATCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTA1MTAxMTA3MjcwOFowIwYJKoZIhvcNAQkEMRYEFDbXTnOl0QH1ZBx0Xq7eKylKzTucMA0GCSqGSIb3DQEBAQUABIGATNCEYM1TZjaR0VYpBF7qxq1+wc5uKxd2L/n8hxku3r1YeoQnTTpfBfePw3QKpfGR47BG2s9C6LDzHfJSJMkn1+N/r9+0yq49tjDz4iwAZkxib1YGWE0RfZBpT+1ByUqDrqrLXySAMoV67VDqPhJrisrYrBrUVnzYQWsTItgvy0A=-----END PKCS7-----">
</form></td>
                <td align="center">
<a target="_blank" href="https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=evilborg2001%40yahoo%2ecom&item_name=CastPodder&item_number=open%2d0&page_style=PayPal&no_shipping=1&return=http%3a%2f%2fwww%2ecastpodder%2enet%2fpaypal%2fthank_you%2ephp&cancel_return=http%3a%2f%2fwww%2ecastpodder%2enet&cn=Add%20your%20comments&tax=0&currency_code=USD&lc=US&bn=PP%2dDonationsBF&charset=UTF%2d8"><img src="https://www.paypal.com/en_US/i/btn/x-click-but04.gif" alt="Donate" border="0"></a>
</td>
        </tr>
        <tr>
                <td align=center><small>Donate $5 USD</small></td>
                <td align=center><small>Donate $10 USD</small></td>
                <td align=center><small>Donate $20 USD</small></td>
                <td align=center><small>Donate $50 USD</small></td>
                <td align=center><small>Donate $?? USD</small></td>
        </tr>
        </table>
